### ISSUE TITLE
Update to version 0.5.0

### ISSUE THREAD

**Issue by rafu1987** [TYPO3-Caretaker/caretaker#10]
After an update of both extensions "caretaker" and "caretaker_instance" to versions 0.5.0 and TYPO3 Update to version 6.2.3, I get the following error:

![caretaker](http://s1.directupload.net/images/140703/ejgxuoa2.jpg)

**Comment by etobi** [comment]
I just pushed a fix, so the loading order of caretaker and caretaker_instance does not matter anymore. I think this solves the issue.
