### ISSUE TITLE
"Caretaker testservice not found" in combination with Scheduler

### ISSUE THREAD

**Issue by larsgentz** [TYPO3-Caretaker/caretaker#11]
Hi Caretaker-Team,

thanks for the Version 0.5.0. My first tests on typo3 6.2.3 showing nice results. 

But i am having this problem:

I tried to configure the Test "Typo3 -> Version" with parameter 6.2.latest. 
When saving this Test I got this hint: "No TYPO3 version information available. Please add "TYPO3 Versionnumbers Update" to your scheduler queue."

After that i activated the Extension "Scheduler" in the Extension Manager, configured the "Typo3 Versionnumbers Update" in the caretaker section of the dropdown with 3600 sec. intervall and saved this task. 

When i switch back to the caretaker overview and select any of my Tests i get one of the following erros:
![image](https://cloud.githubusercontent.com/assets/219814/3479328/e0c88980-034f-11e4-89c9-22cd16d585dd.png)

Selecting the instance, Instance-Group, Test-Group works fine. But not selecting the Test. 

Here some informations about my environment:
Typo3 Version an Caretaker Server: 6.2.3
Caretaker (cartaker) Version 0.5.0
Cartaker Client (caretaker_instance) Version 0.5.0
Scheduler (scheduler) Version 6.2.0

Thanks a lot in advance and please let me know if I can help you with some further tests or in any other way!

Cheers,
Lars

**Comment by Cretection** [comment]
https://forge.typo3.org/issues/64268
