### ISSUE TITLE
Empty result with TYPO3 6.1

### ISSUE THREAD

**Issue by arnekolja** [TYPO3-Caretaker/caretaker#14]
I am receiving an empty result for every test that queries TYPO3, e.g. checking for insecure extensions or checking the TYPO3 version:

    Command execution failed: Empty result returned

I triple-checked the public keys on both sides, I think that's not the problem. Another instance that's taken care of and that's running 6.2 works, but this 6.1 instance is not.

If I can be of any help, please tell me how to further troubleshoot it :-)

**Comment by etobi** [comment]
Did you check the private key for the instance, too?
