### ISSUE TITLE
Advanced Notifications + Roles

### ISSUE THREAD

**Issue by s2b** [TYPO3-Caretaker/caretaker#15]
We use the Advanced Notification Service together with notification roles to deliver different notifications to recipients. This is our setup:

2 roles:

* admin
* security

2 strategies:

* new error [admin and security]
* error resolved [admin]

where "new error" looks like this:

	conditions {
		event = updatedTestResult
		newState = ERROR,WARNING,UNDEFINED
		previousDifferingState = !ERROR
		onlyIfStateChanged = 1

		schedule {
			start = 8
			end = 23
			saturday {
				start = 10
				end = 23
			}
			sunday {
				start = 10
				end = 23
			}
		}
	}

	rules {
		sendMail {
			exit {
				mailError {
					roles = admin
				}
				mailSecurityError {
					roles = security
				}
			}
		}
	}

Both exitpoints use the email service, but with different attributes (e. g. subject)

Then we assigned the "security" role to our TYPO3-specific tests (e. g. core version, insecure extensions), the "admin" role to the remaining tests (HTTP, Selenium). This is how our test tree looks like:

* Instance Group [contacts: 2 with role "admin", 1 with role "security"; both notification strategies]
  * Instance
    * TYPO3 4.5 (test group)
      * TYPO3: Version 4.5 (test) [role: "security"]
    * HTTP: Root (test) [role: "admin"]

However the notification roles don't work as we expected. The "security" contact receives notifications for:

* TYPO3: Version 4.5 - ok
* HTTP: Root - not ok

However it seems to work fine for the two "admin" contacts:

* HTTP: Root - ok

Did we do something wrong with the configuration here or is this a bug?

**Comment by etobi** [comment]
awesome you got so far without proper documentation :-)

The issue is, after checking the "conditions" *all* exitpoints get triggered. In your case this would mean the first exitpoint sends the mail to admin, the second exitpoint sends the mail to security. Thus both got mails.

But i see your point and what you want to archive. I will check it.

**Comment by etobi** [comment]
okay.. seems like the "roles" in the TestNode are not used anywhere in the code.

**Comment by etobi** [comment]
I implemented a new condition "rules" which you can use on your exitpoints to just trigger the one with the matching roles.

```
rules {
    sendMail {
        exit {
            mailError {
                conditions.roles = admin
                roles = admin
            }
            mailSecurityError {
                conditions.roles = security
                roles = security
            }
        }
    }
}
```

commited in the branch "7compatible"
