### ISSUE TITLE
Command execution failed: Request Session Token failed

### ISSUE THREAD

**Issue by NeoBlack** [TYPO3-Caretaker/caretaker#16]
I get a lot of mails because really often anything gets wrong. The mails contains the following messages:

*Warning->Undefined example.com:Find extensions updates* instance_1_test_7
Command execution failed: Request Session Token failed: No Response/Timeout (Total-Time: 0)

Any ideas what happens here? This happens not only for one instance but also not for all. Looks like a timeout problem!? Maybe any hint where and who I can debug it?

**Comment by etobi** [comment]
Hej NeoBlack,
if you want to debug the timeout, you might want to write some details in a log. Have a look at  EXT:caretaker_instance/classes/class.tx_caretakerinstance_RemoteCommandConnector.php around line 209 where the tx_caretakerinstance_RequestSessionTimeoutException is thrown. Write $httpRequestResult in e.g. a log file. It contains the response from curl_exec() and some connection details from curl_getinfo().

I hope this helps to find the cause. Let me/us know.

regards
   tobias

**Comment by NeoBlack** [comment]
Hi Tobi,
thanks, I will give it a try, thx.
