### ISSUE TITLE
The commit "allow records on root level" breaks all configured Flexforms

### ISSUE THREAD

**Issue by christophlehmann** [TYPO3-Caretaker/caretaker#19]
As of http://cweiske.de/tagebuch/typo3-record-on-root-page.htm you should use

rootLevel = -1

not 

rootLevel = 1

I think It's okay for new installations, but not for configured installations.

**Comment by etobi** [comment]
already fixed in e7189a57f6bb89de4306f777d63ae265dbc921d4
