### ISSUE TITLE
TYPO3 version 6.2.9 is installed, but >= 6.2.10rc1 <= 6.2.999 expected.

### ISSUE THREAD

**Issue by christophlehmann** [TYPO3-Caretaker/caretaker#20]
Can we exclude release candidate versions since they are *not stable* and should not be used in production?

**Comment by alexanderfiss** [comment]
This would be a very nice option. +1

**Comment by christophlehmann** [comment]
This check is done in the caretaker_instance ...

File: services/class.tx_caretakerinstance_TYPO3VersionTestService.php
-  $latestVersions = t3lib_div::makeInstance('t3lib_Registry')->get('tx_caretaker', 'TYPO3versions');
+ $latestVersions = t3lib_div::makeInstance('t3lib_Registry')->get('tx_caretaker', 'TYPO3versionsStable');

You only need to do it in your caretaker installation.

**Comment by etobi** [comment]
an option/checkbox is implement. Release will follow soon
