### ISSUE TITLE
BE-User (non-Admin) cannot create new Instances

### ISSUE THREAD

**Issue by alexanderfiss** [TYPO3-Caretaker/caretaker#21]
Hi,

i have a Problem with creating new Instances as a BE-User – there is only one tab "Test Configuration".
I'm going over List-Module, the Instances are in a Folder and i can see my Instancegroup, Contacts and Instances, but creating and editing only shows the Test-Tab (editing the Instance-Group, i see nothing).

In the BE Usergroup, all caretaker items (from Instancegroup till Test) are selected and the group also has access to the Folder.

Please see attached images.

![instance](https://cloud.githubusercontent.com/assets/6135827/8143461/94f98910-11ad-11e5-829b-cc7e8c61a2c0.png)
![instancegroup](https://cloud.githubusercontent.com/assets/6135827/8143460/94f93942-11ad-11e5-8990-949f3058f01c.png)
![usergroup](https://cloud.githubusercontent.com/assets/6135827/8143459/94f7f8e8-11ad-11e5-8cfe-0e0032d8aa44.png)

TYPO3-Version: 6.2.13
Caretaker + Caretaker_Instance: 0.5.2

Regards,
Alex

**Comment by etobi** [comment]
The (almost) all fields were configure in TCA as "exclude = 1". Thus only admin-user could see these fields. As I dont see an advantage to be able to configure the access per field (which doesn't work as you reported) I removed the exclude property from all columns.
Fix is pushed. Release to TER will follow soon.
