### ISSUE TITLE
Advanced notifications don't send mails in 0.6 with TYPO3 6.2

### ISSUE THREAD

**Issue by christophlehmann** [TYPO3-Caretaker/caretaker#25]
I just updated from TYPO3 4.5 and now i don't get mails

**Comment by etobi** [comment]
Did you try the 7compatible branch?

**Comment by christophlehmann** [comment]
Yes, it's broken in 6.2. Autoloading some classes fail and others.

When the branch should also work with 6.2 i will try to investigate some time and try to fix such issues.

You released the 0.6 in TER. Do you get Mails with that version?

**Comment by etobi** [comment]
Yes. the goal is, to merge 7compatible into master and drop support for 4.5.
I need to test/check sending mails in 0.6 and i hope i can do that in the next days.
If you could investigate on it, I would really appreciate that. :-)

**Comment by etobi** [comment]
the autoloader issue is fixed with c5af836

**Comment by etobi** [comment]
sending mails works for me, so i guess the problem was the broken auto loader.
If your issue still exists, please file a new issue and post your configuration/strategy there.

regards
   tobias
