### ISSUE TITLE
TYPO3 version numbers update task fails

### ISSUE THREAD

**Issue by hannesbochmann** [TYPO3-Caretaker/caretaker#26]
The location of the json feed for the releases has been changed. It is now https://get.typo3.org/json.

With the old address I get the following warning:
PHP Warning: Invalid argument supplied for foreach() in ...typo3conf/ext/caretaker/classes/helpers/class.tx_caretaker_LatestVersionsHelper.php line 58

This is because the curl request returns an empty string. 
I think three thinks should be done in tx_caretaker_LatestVersionsHelper:
- change "protected static $releaseJsonFeed = 'http://get.typo3.org/json';" to "protected static $releaseJsonFeed = 'https://get.typo3.org/json';"
- add the curl option to follow redirects with the following function call: curl_setopt($curl, CURLOPT_FOLLOWLOCATION, TRUE);
- there should be a check if line 57 returns an array, if not throw an exception or write a devlog entry, explaining that the json feed may not be longer available.

**Comment by etobi** [comment]
Thanks for your report, debugging and your suggestions.
Could you create a pull request for this?
