### ISSUE TITLE
$releaseJsonFeed with https

### ISSUE THREAD

**Issue by huersch** [TYPO3-Caretaker/caretaker#28]
The cronjob to update the TYPO3 Versions failed with the following message:
Execution failed: 1, PHP Warning: Invalid argument supplied for foreach() in /var/www/html/monitor-curodesign-de/typo3conf/ext/caretaker/classes/helpers/class.tx_caretaker_LatestVersionsHelper.php line 59

I updated the file class.tx_caretaker_LatestVersionsHelper.php in line 54 from 
protected static $releaseJsonFeed = 'http://get.typo3.org/json';
to 
protected static $releaseJsonFeed = 'https://get.typo3.org/json';

**Comment by etobi** [comment]
I think this is already fixed in current master (https://github.com/TYPO3-Caretaker/caretaker/blob/master/classes/helpers/class.tx_caretaker_LatestVersionsHelper.php#L54).

Will be released in TER soon(-ish)
