### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by andyhirsch** [TYPO3-Caretaker/caretaker#29]
New installation of 0.7.3 (also tried 0.7.1) on TYPO3 7.4.0:

Overview throws

PHP Warning: Invalid argument supplied for foreach() in typo3conf/ext/caretaker/mod_overview/index.php line 222

TYPO3 6.2.15 is ok

**Comment by etobi** [comment]
Thanks for your report. Could you check, if your issue is solved by d91228f?

**Comment by andyhirsch** [comment]
Now:
left pane: Fatal error: Class 'template' not found in typo3_src-7.4.0/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4343

right pane: Fatal error: Call to undefined method TYPO3\CMS\Core\Page\PageRenderer::enableExtJSQuickTips() in typo3conf/ext/caretaker/mod_overview/index.php on line 91

**Comment by etobi** [comment]
hmm.. okay.. thanks.. i will investigate on this

**Comment by etobi** [comment]
should be fixed with #36 in current master
