### ISSUE TITLE
Fatal error: Class 'tx_caretaker_tceFunc_selectTreeView' not found (from TYPO3 Forge)

### ISSUE THREAD

**Issue by hannesbochmann** [TYPO3-Caretaker/caretaker#32]
Editing / adding instances or instancegroups generates fatal error:

Fatal error: Class 'tx_caretaker_tceFunc_selectTreeView' not found in /home/t3caretaker/t3ct.coupling-media.com/.secure/typo3_src-6.2.15/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4434

All-Cache was cleared.

TYPO3-Version: 6.2.15
caretaker-Version: 0.7.3
PHP-Version: 5.5.29

The file name of the class is wrong. In the autoload it's class.tx_caretaker_tceFunc_selectTreeView.php but the actual file name is class.tx_caretaker_tcefunc_selecttreeview.php. Simply rename the file.

Btw, I think this error occurs not on Windows as filenames are treated case insensitive.

**Comment by etobi** [comment]
fixed
