### ISSUE TITLE
Testrunner fails if lock could not be acquired

### ISSUE THREAD

**Issue by hannesbochmann** [TYPO3-Caretaker/caretaker#34]
Why does the testrunner return false if the lock could not be acquired? Should this not be fine? It should be enough to not update the test results in this case. 
Why at all is the locking required? Should users not take care on their own that no testrunner tasks exist for the same node id that can run in parallel?

**Comment by etobi** [comment]
i think the locking was introduced to make sure two running test runner wont conflict when updating e.g. the state of a common parent node.

Also I don't think we are going to put any afford into changing this.
However, if you or someone else would come up with a pull request, I will review it!

**Comment by etobi** [comment]
closed because we are not going to fix it.
