### ISSUE TITLE
Override test configuration in BE does not work with FormEngine (7.5+)

### ISSUE THREAD

**Issue by thommyhh** [TYPO3-Caretaker/caretaker#39]
Due to the switch from TCEforms to FormEngine (since 7.5) the hook, that rendered the test configuration override and curl option items does not work anymore. I tried to make it work, but it wouldn't because of the flex form field of the "test configuration" inside the flex form section of test configurations (recursive flex form).

I asked on the Slack core dev channel: Christian Kuhn said, recursive flex form are not supported.

My idea is to migrate the flex form sections to inline records (tx_caretaker_instance_testconfiguration_override, tx_caretaker_instance_curl_option) in two separate fields. I would add a command controller to migrate the flex form sections to inline records and add an option in the extension configuration to enable the new mechanism (before 7.5, enabled automatically for 7.5 and later). This would use the given TYPO3 APIs and does not require any hooks.

I could work on this topic but I need your opinion. What to you think about the idea?

**Comment by thomashempel** [comment]
I would prefer to have only one type of "override". Overriding curl options and test settings are  basically the same, aren't they?

**Comment by thommyhh** [comment]
Ok, I'll give it a try.

**Comment by etobi** [comment]
@thommyhh this is solved by your PR #38, right?
