### ISSUE TITLE
Error in tt_address

### ISSUE THREAD

**Issue by t3premium** [TYPO3-Caretaker/caretaker#41]
Adding a contact record manually causes following error:
2: SQL error: 'Unknown column 'tx_caretaker_xmpp' in 'field list'' (tt_address:NEW56661ae6beaa93.91742561)

**Comment by etobi** [comment]
You could just create the column "tx_caretaker_xmpp" in "tt_address".
We don't create this column via ext_tables.sql anymore, as the caretaker does not depend on tt_address anymore.
For backwards compatibility the caretaker uses tt_address, if it is installed. However, it's now recommended to NOT use "tt_address", but "tx_caretaker_contactaddress" instead.
