### ISSUE TITLE
TYPO3 7.6.9 as Server, 6.2.25 instance - Latest check not working

### ISSUE THREAD

**Issue by robsonrobi** [TYPO3-Caretaker/caretaker#46]
Hello.

We are getting an error, checking the latest TYPO3 6.2.x Version.
In the instance 6.2.25 is installed and the test says, 6.2.17 is not set ?
Seems as caretaker is not up to date regarding the latest core version?

We love caretaker and would be cool, if that can be fixed soon.

Best wishes
robsonrobi

**Comment by etobi** [comment]
Caretaker uses https://get.typo3.org/json to get the latest versions available.
There is a scheduler task to fetch the version informations ("TYPO3 Versionnumbers Update"). Could you check if that task is running regularly in your installation?

**Comment by etobi** [comment]
Hej robsonrobi,

would apprechiate to get some feedback regarding the scheduler task in your setup.

kind regards
   tobias

**Comment by robsonrobi** [comment]
Hey Tobias.

Sorry, for my late reply. You were right, the scheduler was not working, but now everything is fine!

THANK YOU

**Comment by etobi** [comment]
Thanks for your feedback. I'm glad it's working for you now :-)
