### ISSUE TITLE
I have a fatal error in the caretaker extension

### ISSUE THREAD

**Issue by ChristianLauckert** [TYPO3-Caretaker/caretaker#51]
PHP Catchable fatal error:  Argument 2 passed to TYPO3\CMS\Core\Utility\ArrayUtility::mergeRecursiveWithOverrule() must be of the type array, null given, called in /html/typo3conf/ext/caretaker/Classes/services/notifications/advanced/class.tx_caretaker_AdvancedNotificationService.php on line 123 and defined in /html/typo3_src-6.2.22/typo3/sysext/core/Classes/Utility/ArrayUtility.php on line 517

how can i do to fix this? 

please help me

**Comment by etobi** [comment]
Seems like a missing guard-cluase in the code of the AdvancedNotifications. I'll push a fix in the next days.
However as a woraround, try to add at least one "condition" to your strategy config.

```
conditions {
	event = updatedTestResult
}
```

**Comment by ChristianLauckert** [comment]
Thank you very much:-)

it seems that it works now.
