### ISSUE TITLE
Find extension updates -> Don't show extensions for higher versions

### ISSUE THREAD

**Issue by ste101** [TYPO3-Caretaker/caretaker#62]
For example if I have TYPO3 6.2 and I'm using t3adminer than 1.4.2 is the highest possible version.
The test shows the following under 'warnings':
Extension t3adminer is installed in Version 1.4.2. Latest is 7.0.8.
'Find extensions updates' should check the TYPO3 version.

**Comment by ste101** [comment]
I tried to find the file where this test happens but I wasn't able. Could anyone give me a hint?

**Comment by IchHabRecht** [comment]
This problem should be fixed with the pull request https://github.com/TYPO3-Caretaker/caretaker_instance/pull/42
