### ISSUE TITLE
Update for 8.7 ?

### ISSUE THREAD

**Issue by ses** [TYPO3-Caretaker/caretaker#79]
Hi Team,

Is a new version / new updated for T3 8.7 planned?

Thanks,
Sebastian

**Comment by IchHabRecht** [comment]
I think there aren't any plans to upgrade caretaker (server) to 8.7 yet.

**Comment by ses** [comment]
y?

**Comment by etobi** [comment]
Right, no plans to make the caretaker server compatible with 8.7+

However, the caretaker_instance is :-)

**Comment by ingeniumdesign** [comment]
okay, but can u update the caretaker_server for php7 ?

**Comment by claude27** [comment]
Are there perhaps now new plans? ;-)
I actually managed to get it do work in 8.7 with some minor adjustments (mostly for PHP 7.0), the frontend looks good but I didn't get to work the backend module, see https://docs.typo3.org/typo3cms/extensions/core/8.7/Changelog/8.0/Breaking-72405-RemovedTraditionalBEModulesHandling.html
