### ISSUE TITLE
PHP Warning with imagepng

### ISSUE THREAD

**Issue by beardcoder** [TYPO3-Caretaker/caretaker#91]
This warning will be spawn if you use the refresh button.
Ajax URL:` index.php?ajaxID=tx_caretaker%3A%3Anodegraph&node=instance_68_test_73&duration= 86400`

```PHP Warning: imagepng(/Web/): failed to open stream: Is a directory in /Web/typo3conf/ext/caretaker/Classes/renderer/chart/class.tx_caretaker_ChartRendererBase.php line 413```

System: TYPO3 v7
Caretaker Version: 0.8.0

**Comment by IchHabRecht** [comment]
Hi @beardcoder,

would you mind to check if your problem is solved with https://github.com/TYPO3-Caretaker/caretaker/pull/82 (available in current repository master branch)?

Thank you very much.

**Comment by scheibome** [comment]
Hi @IchHabRecht it does'nt work for me. I have the same following error.

$filename give me aus output:

> Resource id #174

#1: PHP Warning: imagepng(..../Web/): failed to open stream: Is a directory in /..../Web/typo3conf/ext/caretaker/Classes/renderer/chart/class.tx_caretaker_ChartRendererBase.php line 413

System: TYPO3 v7
Caretaker Version: currentMaster
